<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { RouterLink, useRoute } from 'vue-router'
import { api, errorMessage, type Subscription } from '../api'
const route = useRoute(); const item = ref<Subscription>(); const processed = ref<Record<string, unknown>[]>([]); const tasks = ref<Record<string, unknown>[]>([]); const error = ref('')
async function load() { try { const id = Number(route.params.id); const rss = await api.subscriptions(); item.value = rss.subscriptions.find(value => value.id === id); processed.value = (await api.processed(id)).items as Record<string, unknown>[]; tasks.value = (await api.tasks(id)).tasks as Record<string, unknown>[] } catch (e) { error.value = errorMessage(e) } }
onMounted(load)
</script>
<template><div class="page-header"><div><RouterLink class="back-link" to="/rss">Back to RSS</RouterLink><h1>Subscription details</h1><p v-if="item" class="page-subtitle error-cell">{{ item.url }} / {{ item.target_folder }}</p></div></div><p v-if="error" class="alert error">{{ error }}</p><section class="section-block"><h2>Processed items</h2><div class="table-wrap"><table><thead><tr><th>Title</th><th>Hash</th><th>Processed</th></tr></thead><tbody><tr v-for="entry in processed" :key="String(entry.id)"><td>{{ entry.title || 'Untitled' }}</td><td class="error-cell">{{ entry.item_hash }}</td><td>{{ entry.processed_at }}</td></tr><tr v-if="!processed.length"><td colspan="3" class="empty-cell">No processed items.</td></tr></tbody></table></div></section><section class="section-block"><h2>Download tasks</h2><div class="table-wrap"><table><thead><tr><th>Hash</th><th>Cloud</th><th>Status</th><th>Added</th></tr></thead><tbody><tr v-for="entry in tasks" :key="String(entry.id)"><td class="error-cell">{{ entry.item_hash }}</td><td>{{ entry.cloud_name }}</td><td>{{ entry.status }}</td><td>{{ entry.added_at }}</td></tr><tr v-if="!tasks.length"><td colspan="4" class="empty-cell">No download tasks.</td></tr></tbody></table></div></section></template>
